language: node_js
node_js:
  - "8.5.0"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


services:
  - postgresql

before_script:
  - psql -c 'drop database if exists sms_api_test;' -U postgres
  - psql -c 'create database sms_api_test;' -U postgres
  - NODE_ENV=test npm run migrate

after_success:
  - npm run coveralls

addons:
  postgresql: "9.3"
